name: CI

on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:

jobs:
  deploy-draft-new:
    name: draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate HTML document
        run: |
          mkdir -p example
          echo -e "<pre>$(date -u)\n$GITHUB_SHA\n$GITHUB_REF</pre>" > example/index.html

      - name: Deploy draft to Netlify
        uses: ./
        id: netlify
        with:
          args: 'deploy --json --dir \"./example\" --message \"draft [${{ github.sha }}]\"'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_NEW }}

      - name: Action outputs
        run: |
          echo "NETLIFY_OUTPUT: ${{ steps.netlify.outputs.NETLIFY_OUTPUT }}"

  deploy-prod-new:
    name: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate HTML document
        run: |
          mkdir -p example
          echo -e "<pre>$(date -u)\n$GITHUB_SHA\n$GITHUB_REF</pre>" > example/index.html

      - name: Deploy to Netlify
        uses: ./
        id: netlify
        with:
          args: 'deploy --prod --json --dir \"./example\" --message \"production [${{ github.sha }}]\"'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_NEW }}

      - name: Action outputs
        run: |
          echo "NETLIFY_OUTPUT: ${{ steps.netlify.outputs.NETLIFY_OUTPUT }}"
